name: quality-control
run-name: Quality Control
on: [push]
jobs:
  quality-control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements-dev.txt
      - run: black --check .
      - run: flake8 .
      - run: python manage.py check
      - run: python manage.py makemigrations --check
